INCLUDES = -I../include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/drivers/cc110x_ng/include -I../lib -I$(RIOTCPU)/$(CPU)/include -I../net -I../../core/include -I$(RIOTBASE)/drivers/cc2420/include -I$(RIOTBASE)/sys/net/ieee802154/ -I$(RIOTBOARD)/redbee-econotag/drivers/include
MODULE =transceiver

include $(MAKEBASE)/Makefile.base


