INCLUDES = -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/sys/posix/include -Iinclude -I$(RIOTBASE)/sys/net/include -I$(RIOTBASE)/drivers/cc110x_ng/include
MODULE =pnet

include $(RIOTBASE)/Makefile.base
